"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['atvusb-creator.py']
DATA_FILES = [
  'qt.conf',
  'tools',
  'payloads',
  '../staging',
  '../downloads',
  ]
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
