"""
This is a setup.py script generated by py2applet

Usage:
    python setup-osx.py py2app
"""
# SDD - This need more dev to get working
#

from setuptools import setup
import py2app

setup(
    app = ['atvusb-creator.py'],
    data_files = [
        "LICENSE.txt",
        ("tools", []),
        ("data", [
            "data/atvusb.icns",
        ]),
        ("payloads", [
            "payloads/atvusb_256MB_disk.img.zip",
            "payloads/atvusb_256MB_hfs_partition.img.zip",
        ]),
        ("downloads", [])
    ],
    #options={'py2app': {'argv_emulation': True, 'resources': True}},
    #Setup_requires=['py2app'],
)
